grafana:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    enabled: true
    type: pvc
    storageClassName: gp3
    size: 10Gi
  service:
    type: LoadBalancer
  grafana.ini:
    server:
      root_url: https://grafana.devcloudproject.com
    auth:
      disable_login_form: true
      oauth_auto_login: true
      signout_redirect_url: "https://auth-devcloudproject.auth.us-east-1.amazoncognito.com/logout?client_id=16c8e7la37sl1v5tcrkukple8s&logout_uri=https://grafana.devcloudproject.com/"
    auth.generic_oauth:
      enabled: true
      name: Amazon Cognito
      allow_sign_up: true
      client_id: 16c8e7la37sl1v5tcrkukple8s
      scopes: openid profile email
      auth_url: https://auth-devcloudproject.auth.us-east-1.amazoncognito.com/oauth2/authorize
      token_url: https://auth-devcloudproject.auth.us-east-1.amazoncognito.com/oauth2/token
      api_url: https://auth-devcloudproject.auth.us-east-1.amazoncognito.com/oauth2/userInfo
      role_attribute_path: contains(cognito:groups[*], 'Admin') && 'Admin' || 'Viewer'
  envFromSecret: grafana-sso-credentials
  additionalDataSources:
    - name: Elasticsearch
      type: elasticsearch
      access: proxy
      url: http://elasticsearch-master.logging.svc.cluster.local:9200
      database: "logs-*"
      jsonData:
        timeField: "@timestamp"
        esVersion: "8.0.0"

prometheus:
  prometheusSpec:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}

kube-state-metrics:
  metricLabelsAllowlist:
    - nodes=[*]
