apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: db-secrets
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: devsecops/amazon-app/db-secrets
  data:
  - secretKey: db_password
    remoteRef:
      key: {{ .Values.db.masterSecretArn }}
      property: password
