# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-1"
  default_tags {
    tags = {
      Project     = "Amazon-Clone-DevSecOps"
      ManagedBy   = "Terragrunt"
      Environment = "dev"
    }
  }
}
